spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_aioceaneye_java
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8000
logging.level.org.springframework.security: DEBUG
